# Generated by Django 4.0.1 on 2022-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindfulcheck',
            name='career',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='mindfulcheck',
            name='overall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
