# Generated by Django 4.0.1 on 2022-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mindfulcheck_career_mindfulcheck_overall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferences',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='gaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='hiit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='meditation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='puzzles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='yoga',
            field=models.BooleanField(default=False),
        ),
    ]
