# Generated by Django 4.0.1 on 2022-01-30 09:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mindfulcheck_career_mindfulcheck_overall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.URLField(max_length=1024)),
                ('vid_length', models.CharField(max_length=12)),
                ('preferences', multiselectfield.db.fields.MultiSelectField(choices=[('yoga', 'Yoga'), ('meditation', 'Meditation'), ('music', 'Music'), ('puzzles', 'Puzzles'), ('gaming', 'Gaming'), ('hiit', 'HIIT'), ('reading', 'Reading')], max_length=100)),
            ],
        ),
    ]
