# Generated by Django 4.0.1 on 2022-01-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
